version: '3.10'

services:
  blts:
    build: .
    command: /bin/sh -c "python manage.py makemigrations && python manage.py makemigrations account && python manage.py makemigrations main && python manage.py makemigrations session && python manage.py makemigrations tests && python manage.py migrate session && python manage.py migrate tests && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"
    container_name: blts
