# Generated by Django 5.0.4 on 2024-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tests/img/<django.db.models.fields.CharField>', verbose_name='Картинка'),
        ),
    ]
