# Generated by Django 5.0.4 on 2024-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/img/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='test',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tests/img/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
