# Generated by Django 5.0.4 on 2024-05-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer_for_task',
        ),
        migrations.RemoveField(
            model_name='answer_from_user',
            name='test',
        ),
    ]
