# Generated by Django 5.0.4 on 2024-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_tests_for_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests_for_user',
            options={'verbose_name': 'Ответ пользователя на тесты', 'verbose_name_plural': 'Ответы пользователя на тесты'},
        ),
        migrations.AddField(
            model_name='tests_for_user',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='tests_for_user',
            name='ans',
            field=models.ManyToManyField(to='tests.answer_from_user', verbose_name='Ответы'),
        ),
    ]
